const en = {
  capacity: 'Active history is full across all projects. Archive saved records to free space, then retry. A new ID does not free capacity.',
  storageError: 'History storage is unavailable. Your input is retained. Retry after resolving storage access.',
  conflictError: 'This saved correction changed or is immutable. Your input is retained; refresh history or continue with a new ID.',
  archivedError: 'This correction is archived. Restore it from history before editing or copying.',
  invalidError: 'The correction export is invalid or too large. Existing history was preserved.',
  projectError: 'The project changed or this export belongs to another project. Select its original project.',
  clipboardError: 'Clipboard access failed. Your text is retained; retry copying.',
  manageHistory: 'Manage correction history', activeHistory: 'Active', archivedHistory: 'Archived', refreshHistory: 'Refresh history',
  usage: 'Active storage · all projects', bytes: 'bytes', archivedCount: 'Archived in this project',
  historyScope: 'Records below belong to this project. Capacity is shared across projects; switch projects to manage their records.',
  archive: 'Archive', restore: 'Restore', exportRecord: 'Copy recovery JSON', importRecord: 'Restore recovery JSON', importText: 'Recovery JSON',
  exported: 'Recovery JSON copied. Keep it outside inspected projects. This is not agent delivery.', imported: 'Recovery JSON restored to active history.',
  archiveNote: 'Archiving preserves IDs and responses and frees active capacity. It enables durable history with an original JSON backup; older Inspector versions cannot read the migrated store.',
  confirmHistory: 'Confirm history action', cancelHistory: 'Cancel', archivedSaved: 'Record archived. It remains available in archived history.', restoredSaved: 'Record restored with its original ID and revision.',
  previousPage: 'Previous page', nextPage: 'Next page', emptyHistory: 'No saved records on this page.', viewRecord: 'View correction',

  recover: 'Continue with a new correction ID', recoveryHint: 'If another window changed this draft, preserve your text under a new ID. Reload to read the saved version.',
  title: 'My request and AI understanding', empty: 'No structured report. Open the original documents; an interpretation cannot be inferred.',
  request: 'Request', interpretation: 'AI interpretation', progress: 'Requirement progress', decision: 'Important decisions', response: 'Correction responses',
  source: 'Open report source', userSource: 'User request source', scope: 'Included scope', excluded: 'Excluded scope', assumptions: 'Assumptions', remaining: 'Remaining work',
  impact: 'Reported impact', alternatives: 'Alternatives', reason: 'Reported reason', owner_question: 'Your decision is needed',
  report: 'AI report · not independently verified', observed: 'Read at', revision: 'Requirement revision',
  correct: 'Correct this interpretation', correction: 'Your correction', save: 'Save draft', copy: 'Copy request', next: 'New correction',
  saved: 'Draft saved in Inspector', error: 'Could not save or copy. Your text is retained.', preview: 'Request text preview',
  sealed: 'Copy prepared · success unconfirmed', draft: 'Draft · not sent', copied: 'Copied · delivery unconfirmed', acknowledged: 'AI acknowledged', planned: 'AI reported change plan', applied: 'AI reported application',
  verification_reported: 'Verification reported · review evidence', unconfirmed: 'Unconfirmed · sources incomplete', conflict: 'Conflicting reports', stale: 'Stale revision',
  warning: 'Some reports are incomplete, stale or conflicting. They cannot establish current completion.',
  note: 'Copy the request into your agent conversation, then re-scan to read its response. Inspector does not send it or write to the project.',
  history: 'Correction history', unknown: 'Unreported', evidence: 'Reported evidence', remainingStatus: 'Remaining', implemented: 'Implementation reported', blocked: 'Blocked',
  noInterpretation: 'No unambiguous interpretation for this revision.', savedOnly: 'Your text stays while opening sources or switching requests and projects. Save or copy to keep it after a reload.', unavailable: 'Evidence source is not in the current bounded documents.',
};
type Copy = typeof en;
const ko: Copy = {
  capacity: '모든 프로젝트가 공유하는 활성 이력이 가득 찼습니다. 저장된 기록을 보관한 뒤 다시 시도하세요. 새 ID로는 공간이 늘어나지 않습니다.',
  storageError: '이력 저장소에 접근할 수 없습니다. 입력은 유지됩니다. 저장소 문제를 해결한 뒤 다시 시도하세요.',
  conflictError: '다른 창에서 저장된 정정이 바뀌었거나 수정할 수 없는 기록입니다. 입력은 유지됩니다. 이력을 새로 읽거나 새 ID로 이어 쓰세요.',
  archivedError: '보관된 정정입니다. 이력에서 복원한 뒤 수정하거나 복사하세요.',
  invalidError: '복구 JSON이 올바르지 않거나 너무 큽니다. 기존 이력은 유지됩니다.',
  projectError: '프로젝트가 바뀌었거나 다른 프로젝트의 기록입니다. 원래 프로젝트를 선택하세요.',
  clipboardError: '클립보드에 복사하지 못했습니다. 입력은 유지됩니다. 다시 복사하세요.',
  manageHistory: '정정 이력 관리', activeHistory: '활성', archivedHistory: '보관됨', refreshHistory: '이력 새로 읽기',
  usage: '활성 저장소 · 모든 프로젝트', bytes: '바이트', archivedCount: '이 프로젝트의 보관 기록',
  historyScope: '아래 기록은 현재 프로젝트에 속합니다. 용량은 모든 프로젝트가 공유합니다. 다른 프로젝트의 기록은 프로젝트를 전환하여 관리하세요.',
  archive: '보관', restore: '복원', exportRecord: '복구 JSON 복사', importRecord: '복구 JSON 복원', importText: '복구 JSON',
  exported: '복구 JSON을 복사했습니다. 검사 대상 프로젝트 밖에 보관하세요. AI에 전달한 것은 아닙니다.', imported: '복구 JSON을 활성 이력에 복원했습니다.',
  archiveNote: '보관하면 ID와 응답을 유지하며 활성 공간을 확보합니다. 원본 JSON 백업을 남기고 장기 이력 저장소로 전환합니다. 이전 Inspector는 전환된 저장소를 읽을 수 없습니다.',
  confirmHistory: '이력 작업 확인', cancelHistory: '취소', archivedSaved: '기록을 보관했습니다. 보관 이력에서 계속 확인할 수 있습니다.', restoredSaved: '원래 ID와 리비전으로 기록을 복원했습니다.',
  previousPage: '이전 페이지', nextPage: '다음 페이지', emptyHistory: '이 페이지에 저장된 기록이 없습니다.', viewRecord: '정정 보기',

  recover: '새 정정 ID로 이어 쓰기', recoveryHint: '다른 창에서 초안이 변경되었다면 새 ID로 입력을 보존하세요. 저장된 버전은 새로고침하면 확인할 수 있습니다.',
  title: '내 요청과 AI의 이해', empty: '구조화된 보고가 없습니다. 원문을 열어 확인하세요. 해석을 추측하지 않습니다.',
  request: '내 요청', interpretation: 'AI의 해석', progress: '요구별 진행', decision: '중요한 선택', response: '정정 응답',
  source: '보고 원문 열기', userSource: '사용자 요청 출처', scope: '포함 범위', excluded: '제외 범위', assumptions: '주요 가정', remaining: '남은 필수 작업',
  impact: '보고된 영향', alternatives: '대안', reason: '보고된 선택 이유', owner_question: '내 결정이 필요한 일',
  report: 'AI 보고 · 독립 검증 전', observed: '읽은 시각', revision: '요구 리비전',
  correct: '해석 바로잡기', correction: '정정할 내용', save: '초안 저장', copy: '요청문 복사', next: '새 정정 작성',
  saved: 'Inspector에 초안을 저장했습니다', error: '저장 또는 복사하지 못했습니다. 입력한 내용은 유지됩니다.', preview: '전달할 요청문 미리보기',
  sealed: '복사 준비됨 · 성공 미확인', draft: '초안 · 미전달', copied: '복사됨 · 전달 미확인', acknowledged: 'AI 수신 확인 보고', planned: 'AI 변경 계획 보고', applied: 'AI 반영 보고',
  verification_reported: '검증 보고 · 근거 검토 필요', unconfirmed: '미확인 · 출처 불완전', conflict: '보고 충돌', stale: '오래된 리비전',
  warning: '불완전하거나 오래된 보고 또는 충돌이 있습니다. 현재 완료의 근거로 사용할 수 없습니다.',
  note: '요청문을 작업 AI 대화에 붙여 넣고, 다시 검사하여 응답을 확인하세요. Inspector가 직접 전달하거나 프로젝트를 수정하지 않습니다.',
  history: '정정 이력', unknown: '미보고', evidence: '보고된 검증 근거', remainingStatus: '남은 요구', implemented: '구현 보고', blocked: '차단됨',
  noInterpretation: '이 리비전에 일치하는 명확한 해석이 없습니다.', savedOnly: '원문을 열거나 요청·프로젝트를 바꿔도 입력이 유지됩니다. 새로고침 후에도 유지하려면 저장하거나 복사하세요.', unavailable: '현재 제한된 문서 조회 범위에 없는 근거입니다.',
};
const ja: Copy = {
  capacity: '全プロジェクト共通の履歴容量が一杯です。保存済み記録を保管してから再試行してください。新しいIDでは空き容量は増えません。',
  storageError: '履歴ストレージを利用できません。入力は保持されています。アクセスを復旧してから再試行してください。',
  conflictError: '別のウィンドウで変更されたか、変更不可の記録です。入力は保持されています。履歴を更新するか新しいIDで続けてください。',
  archivedError: '保管済みの訂正です。履歴から復元してから編集またはコピーしてください。',
  invalidError: '復元JSONが不正か大きすぎます。既存の履歴は保持されています。',
  projectError: 'プロジェクトが変更されたか、別のプロジェクトの記録です。元のプロジェクトを選択してください。',
  clipboardError: 'クリップボードへのコピーに失敗しました。入力は保持されています。再試行してください。',
  manageHistory: '訂正履歴を管理', activeHistory: 'アクティブ', archivedHistory: '保管済み', refreshHistory: '履歴を再読込',
  usage: '全プロジェクト共通の容量', bytes: 'バイト', archivedCount: 'このプロジェクトの保管記録',
  historyScope: '表示中の記録は現在のプロジェクトのものです。容量は全プロジェクト共通です。他の記録はプロジェクトを切り替えて管理してください。',
  archive: '保管', restore: '復元', exportRecord: '復元JSONをコピー', importRecord: '復元JSONを読み込む', importText: '復元JSON',
  exported: '復元JSONをコピーしました。検査対象プロジェクト外に保管してください。AIへの送信ではありません。', imported: '復元JSONをアクティブ履歴に読み込みました。',
  archiveNote: '保管してもIDと応答は保持され、空き容量が増えます。元のJSONをバックアップして永続履歴に移行します。以前のInspectorでは移行後の履歴を読めません。',
  confirmHistory: '履歴操作を確認', cancelHistory: 'キャンセル', archivedSaved: '記録を保管しました。保管履歴から確認できます。', restoredSaved: '元のIDとリビジョンで記録を復元しました。',
  previousPage: '前のページ', nextPage: '次のページ', emptyHistory: 'このページに保存済み記録はありません。', viewRecord: '訂正を表示',

  recover: '新しい訂正IDで続ける', recoveryHint: '別のウィンドウで変更された場合、新しいIDで入力を保持できます。保存済みの版は再読込で確認できます。',
  title: '依頼とAIの理解', empty: '構造化された報告はありません。原文を確認してください。解釈は推測しません。',
  request: '依頼', interpretation: 'AIの解釈', progress: '要件別の進行', decision: '重要な選択', response: '訂正への応答',
  source: '報告の原文を開く', userSource: 'ユーザー依頼の出典', scope: '対象範囲', excluded: '対象外', assumptions: '前提', remaining: '残りの作業',
  impact: '報告された影響', alternatives: '代替案', reason: '報告された理由', owner_question: '判断が必要です',
  report: 'AI報告・独立検証前', observed: '読取時刻', revision: '要件リビジョン',
  correct: '解釈を訂正', correction: '訂正内容', save: '下書きを保存', copy: '依頼文をコピー', next: '新しい訂正',
  saved: 'Inspectorに保存しました', error: '保存またはコピーできませんでした。入力は保持されています。', preview: '依頼文のプレビュー',
  sealed: 'コピー準備済み・成功未確認', draft: '下書き・未送信', copied: 'コピー済み・送信未確認', acknowledged: 'AI受信確認報告', planned: 'AI変更計画報告', applied: 'AI反映報告',
  verification_reported: '検証報告・根拠の確認が必要', unconfirmed: '未確認・出典が不完全', conflict: '報告の競合', stale: '古いリビジョン',
  warning: '不完全、古い、または競合する報告は現在の完了根拠にはなりません。',
  note: '作業AIの会話に貼り付け、再検査で応答を確認してください。Inspectorは送信やプロジェクトの変更を行いません。',
  history: '訂正履歴', unknown: '未報告', evidence: '報告された検証根拠', remainingStatus: '残りの要件', implemented: '実装報告', blocked: 'ブロック中',
  noInterpretation: 'このリビジョンの明確な解釈はありません。', savedOnly: '原文の表示や依頼・プロジェクトの切替でも入力は保持されます。再読込後も保持するには保存またはコピーしてください。', unavailable: '現在の読取対象に含まれない根拠です。',
};
const zh: Copy = {
  capacity: '所有项目共享的活动历史已满。请归档已保存的记录后重试。新ID不会释放容量。',
  storageError: '历史存储不可用，输入已保留。请恢复存储访问后重试。',
  conflictError: '记录已被其他窗口修改或不可更改。输入已保留，请刷新历史或使用新ID继续。',
  archivedError: '此纠正已归档。请先从历史中恢复，再编辑或复制。',
  invalidError: '恢复JSON无效或过大，现有历史已保留。',
  projectError: '项目已切换或记录属于其他项目，请选择原项目。',
  clipboardError: '剪贴板复制失败，输入已保留。请重试。',
  manageHistory: '管理纠正历史', activeHistory: '活动', archivedHistory: '已归档', refreshHistory: '刷新历史',
  usage: '活动存储 · 所有项目', bytes: '字节', archivedCount: '此项目的归档记录',
  historyScope: '以下记录属于当前项目。容量由所有项目共享，请切换项目以管理其他记录。',
  archive: '归档', restore: '恢复', exportRecord: '复制恢复JSON', importRecord: '恢复JSON记录', importText: '恢复JSON',
  exported: '恢复JSON已复制，请保存在检查项目之外。这不是向AI发送。', imported: '恢复JSON已导入活动历史。',
  archiveNote: '归档保留ID与回复并释放活动容量。原始JSON将被备份并转为持久历史存储，旧版Inspector无法读取转换后的存储。',
  confirmHistory: '确认历史操作', cancelHistory: '取消', archivedSaved: '记录已归档，仍可在归档历史中查看。', restoredSaved: '记录已按原ID与修订恢复。',
  previousPage: '上一页', nextPage: '下一页', emptyHistory: '此页没有已保存记录。', viewRecord: '查看纠正',

  recover: '使用新的纠正ID继续', recoveryHint: '若其他窗口修改了草稿，可用新ID保留输入。重新加载可查看已保存的版本。',
  title: '我的请求与AI的理解', empty: '没有结构化报告。请查看原文，不推测AI的理解。',
  request: '我的请求', interpretation: 'AI的理解', progress: '逐项需求进度', decision: '重要选择', response: '纠正回复',
  source: '打开报告原文', userSource: '用户请求来源', scope: '包含范围', excluded: '排除范围', assumptions: '主要假设', remaining: '剩余工作',
  impact: '报告的影响', alternatives: '备选方案', reason: '报告的原因', owner_question: '需要您的决定',
  report: 'AI报告 · 尚未独立验证', observed: '读取时间', revision: '需求修订',
  correct: '纠正理解', correction: '纠正内容', save: '保存草稿', copy: '复制请求', next: '新建纠正',
  saved: '草稿已保存到Inspector', error: '保存或复制失败，输入内容已保留。', preview: '请求文本预览',
  sealed: '复制已准备 · 成功未确认', draft: '草稿 · 未发送', copied: '已复制 · 发送未确认', acknowledged: 'AI报告已收到', planned: 'AI报告变更计划', applied: 'AI报告已应用',
  verification_reported: '验证报告 · 请审查证据', unconfirmed: '未确认 · 来源不完整', conflict: '报告冲突', stale: '旧修订',
  warning: '存在不完整、过期或冲突的报告，不能据此确认当前完成状态。',
  note: '将请求粘贴到工作AI对话，然后重新检查以查看回复。Inspector不会直接发送或修改项目。',
  history: '纠正历史', unknown: '未报告', evidence: '报告的验证证据', remainingStatus: '剩余需求', implemented: '实现报告', blocked: '受阻',
  noInterpretation: '没有与此修订一致的明确理解。', savedOnly: '打开原文或切换请求和项目时会保留输入。保存或复制可在重新加载后保留草稿。', unavailable: '此证据不在当前限定读取范围内。',
};
export const interactionCopy = {en, ko, ja, 'zh-CN': zh};
export type InteractionCopy = Copy;
