const en = {
  recover: 'Continue with a new correction ID', recoveryHint: 'If another window changed this draft, preserve your text under a new ID. Reload to read the saved version.',
  title: 'My request and AI understanding', empty: 'No structured report. Open the original documents; an interpretation cannot be inferred.',
  request: 'Request', interpretation: 'AI interpretation', progress: 'Requirement progress', decision: 'Important decisions', response: 'Correction responses',
  source: 'Open report source', userSource: 'User request source', scope: 'Included scope', excluded: 'Excluded scope', assumptions: 'Assumptions', remaining: 'Remaining work',
  impact: 'Reported impact', alternatives: 'Alternatives', reason: 'Reported reason', owner_question: 'Your decision is needed',
  report: 'AI report · not independently verified', observed: 'Read at', revision: 'Requirement revision',
  correct: 'Correct this interpretation', correction: 'Your correction', save: 'Save draft', copy: 'Copy request', next: 'New correction',
  saved: 'Draft saved in Inspector', error: 'Could not save or copy. Your text is retained.', preview: 'Request text preview',
  sealed: 'Copy prepared · success unconfirmed', draft: 'Draft · not sent', copied: 'Copied · delivery unconfirmed', acknowledged: 'AI acknowledged', planned: 'AI reported change plan', applied: 'AI reported application',
  verification_reported: 'Verification reported · review evidence', unconfirmed: 'Unconfirmed · sources incomplete', conflict: 'Conflicting reports', stale: 'Stale revision',
  warning: 'Some reports are incomplete, stale or conflicting. They cannot establish current completion.',
  note: 'Copy the request into your agent conversation, then re-scan to read its response. Inspector does not send it or write to the project.',
  history: 'Correction history', unknown: 'Unreported', evidence: 'Reported evidence', remainingStatus: 'Remaining', implemented: 'Implementation reported', blocked: 'Blocked',
  noInterpretation: 'No unambiguous interpretation for this revision.', savedOnly: 'Your text stays while opening sources or switching requests and projects. Save or copy to keep it after a reload.', unavailable: 'Evidence source is not in the current bounded documents.',
};
type Copy = typeof en;
const ko: Copy = {
  recover: '새 정정 ID로 이어 쓰기', recoveryHint: '다른 창에서 초안이 변경되었다면 새 ID로 입력을 보존하세요. 저장된 버전은 새로고침하면 확인할 수 있습니다.',
  title: '내 요청과 AI의 이해', empty: '구조화된 보고가 없습니다. 원문을 열어 확인하세요. 해석을 추측하지 않습니다.',
  request: '내 요청', interpretation: 'AI의 해석', progress: '요구별 진행', decision: '중요한 선택', response: '정정 응답',
  source: '보고 원문 열기', userSource: '사용자 요청 출처', scope: '포함 범위', excluded: '제외 범위', assumptions: '주요 가정', remaining: '남은 필수 작업',
  impact: '보고된 영향', alternatives: '대안', reason: '보고된 선택 이유', owner_question: '내 결정이 필요한 일',
  report: 'AI 보고 · 독립 검증 전', observed: '읽은 시각', revision: '요구 리비전',
  correct: '해석 바로잡기', correction: '정정할 내용', save: '초안 저장', copy: '요청문 복사', next: '새 정정 작성',
  saved: 'Inspector에 초안을 저장했습니다', error: '저장 또는 복사하지 못했습니다. 입력한 내용은 유지됩니다.', preview: '전달할 요청문 미리보기',
  sealed: '복사 준비됨 · 성공 미확인', draft: '초안 · 미전달', copied: '복사됨 · 전달 미확인', acknowledged: 'AI 수신 확인 보고', planned: 'AI 변경 계획 보고', applied: 'AI 반영 보고',
  verification_reported: '검증 보고 · 근거 검토 필요', unconfirmed: '미확인 · 출처 불완전', conflict: '보고 충돌', stale: '오래된 리비전',
  warning: '불완전하거나 오래된 보고 또는 충돌이 있습니다. 현재 완료의 근거로 사용할 수 없습니다.',
  note: '요청문을 작업 AI 대화에 붙여 넣고, 다시 검사하여 응답을 확인하세요. Inspector가 직접 전달하거나 프로젝트를 수정하지 않습니다.',
  history: '정정 이력', unknown: '미보고', evidence: '보고된 검증 근거', remainingStatus: '남은 요구', implemented: '구현 보고', blocked: '차단됨',
  noInterpretation: '이 리비전에 일치하는 명확한 해석이 없습니다.', savedOnly: '원문을 열거나 요청·프로젝트를 바꿔도 입력이 유지됩니다. 새로고침 후에도 유지하려면 저장하거나 복사하세요.', unavailable: '현재 제한된 문서 조회 범위에 없는 근거입니다.',
};
const ja: Copy = {
  recover: '新しい訂正IDで続ける', recoveryHint: '別のウィンドウで変更された場合、新しいIDで入力を保持できます。保存済みの版は再読込で確認できます。',
  title: '依頼とAIの理解', empty: '構造化された報告はありません。原文を確認してください。解釈は推測しません。',
  request: '依頼', interpretation: 'AIの解釈', progress: '要件別の進行', decision: '重要な選択', response: '訂正への応答',
  source: '報告の原文を開く', userSource: 'ユーザー依頼の出典', scope: '対象範囲', excluded: '対象外', assumptions: '前提', remaining: '残りの作業',
  impact: '報告された影響', alternatives: '代替案', reason: '報告された理由', owner_question: '判断が必要です',
  report: 'AI報告・独立検証前', observed: '読取時刻', revision: '要件リビジョン',
  correct: '解釈を訂正', correction: '訂正内容', save: '下書きを保存', copy: '依頼文をコピー', next: '新しい訂正',
  saved: 'Inspectorに保存しました', error: '保存またはコピーできませんでした。入力は保持されています。', preview: '依頼文のプレビュー',
  sealed: 'コピー準備済み・成功未確認', draft: '下書き・未送信', copied: 'コピー済み・送信未確認', acknowledged: 'AI受信確認報告', planned: 'AI変更計画報告', applied: 'AI反映報告',
  verification_reported: '検証報告・根拠の確認が必要', unconfirmed: '未確認・出典が不完全', conflict: '報告の競合', stale: '古いリビジョン',
  warning: '不完全、古い、または競合する報告は現在の完了根拠にはなりません。',
  note: '作業AIの会話に貼り付け、再検査で応答を確認してください。Inspectorは送信やプロジェクトの変更を行いません。',
  history: '訂正履歴', unknown: '未報告', evidence: '報告された検証根拠', remainingStatus: '残りの要件', implemented: '実装報告', blocked: 'ブロック中',
  noInterpretation: 'このリビジョンの明確な解釈はありません。', savedOnly: '原文の表示や依頼・プロジェクトの切替でも入力は保持されます。再読込後も保持するには保存またはコピーしてください。', unavailable: '現在の読取対象に含まれない根拠です。',
};
const zh: Copy = {
  recover: '使用新的纠正ID继续', recoveryHint: '若其他窗口修改了草稿，可用新ID保留输入。重新加载可查看已保存的版本。',
  title: '我的请求与AI的理解', empty: '没有结构化报告。请查看原文，不推测AI的理解。',
  request: '我的请求', interpretation: 'AI的理解', progress: '逐项需求进度', decision: '重要选择', response: '纠正回复',
  source: '打开报告原文', userSource: '用户请求来源', scope: '包含范围', excluded: '排除范围', assumptions: '主要假设', remaining: '剩余工作',
  impact: '报告的影响', alternatives: '备选方案', reason: '报告的原因', owner_question: '需要您的决定',
  report: 'AI报告 · 尚未独立验证', observed: '读取时间', revision: '需求修订',
  correct: '纠正理解', correction: '纠正内容', save: '保存草稿', copy: '复制请求', next: '新建纠正',
  saved: '草稿已保存到Inspector', error: '保存或复制失败，输入内容已保留。', preview: '请求文本预览',
  sealed: '复制已准备 · 成功未确认', draft: '草稿 · 未发送', copied: '已复制 · 发送未确认', acknowledged: 'AI报告已收到', planned: 'AI报告变更计划', applied: 'AI报告已应用',
  verification_reported: '验证报告 · 请审查证据', unconfirmed: '未确认 · 来源不完整', conflict: '报告冲突', stale: '旧修订',
  warning: '存在不完整、过期或冲突的报告，不能据此确认当前完成状态。',
  note: '将请求粘贴到工作AI对话，然后重新检查以查看回复。Inspector不会直接发送或修改项目。',
  history: '纠正历史', unknown: '未报告', evidence: '报告的验证证据', remainingStatus: '剩余需求', implemented: '实现报告', blocked: '受阻',
  noInterpretation: '没有与此修订一致的明确理解。', savedOnly: '打开原文或切换请求和项目时会保留输入。保存或复制可在重新加载后保留草稿。', unavailable: '此证据不在当前限定读取范围内。',
};
export const interactionCopy = {en, ko, ja, 'zh-CN': zh};
export type InteractionCopy = Copy;
