import type { Locale } from './i18n';

const en = {
  title: 'Resume comparison',
  introduction: 'Compare saved observations before continuing work. History cannot authorize work, reactivate a deferred packet, or prove verification or acceptance.',
  privacy: 'Optional storage in this device’s app preferences: packet objective, status, gates, paths, source hashes and observation times. Document bodies are not stored. Up to 8 projects and 192 KiB total; older project history may be removed. Records survive app restarts and local address changes.',
  enable: 'Enable and save baseline', compare: 'Compare with saved baseline', close: 'Close comparison',
  replace: 'Use current observation as baseline', clear: 'Clear this project and disable', clearAll: 'Clear all comparison history',
  pinned: 'The baseline stays pinned until you replace or clear it. Refreshes keep only the latest observation alongside it.',
  unavailable: 'A coherent completed inspection with readable state is required. Failed or stale scans do not replace stored observations.',
  newerSaved: 'A newer observation was saved by another view. Rescan this project before comparing or replacing the baseline.',
  storageError: 'Comparison history could not be read or saved. Retry or rescan before replacing the baseline.', retry: 'Retry reading history',
  baseline: 'Saved baseline', current: 'Current observation', latest: 'Latest saved observation',
  observed: 'Inspected at', source: 'Open current source', unknown: 'Unknown', unchanged: 'Unchanged', changed: 'Changed',
  none: 'Not declared', absent: 'File absent', fieldUnknown: 'Not recorded',
  limits: 'Comparison covers retained metadata only. Clipped values or missing hashes remain unknown. Matching hashes do not establish valid verification or permission.',
  omitted: 'Some source paths exceed retention limits and are not included.',
  metadata: 'Declared state', sources: 'Source identities captured by the inspection',
  packet: 'Packet', objective: 'Objective', status: 'Declared status', gates: 'Declared owner gates', spec: 'Active SPEC', handoff: 'Resume checkpoint',
};
export type ResumeCopy = typeof en;
const ko: ResumeCopy = {
  title: '재개 전 변경 비교',
  introduction: '작업을 이어가기 전에 저장된 관찰을 비교하세요. 과거 기록은 작업 권한, 보류된 패킷의 재활성화, 검증 통과나 수락의 근거가 아닙니다.',
  privacy: '선택적으로 이 기기의 앱 설정 저장소에 목표·상태·게이트·경로·출처 해시·관찰 시각을 저장합니다. 문서 본문은 저장하지 않습니다. 최대 8개 프로젝트·총 192 KiB이며 오래된 프로젝트 기록은 제거될 수 있습니다. 앱 재시작이나 로컬 주소 변경 후에도 기록이 유지됩니다.',
  enable: '켜고 비교 기준 저장', compare: '저장된 기준과 비교', close: '비교 닫기',
  replace: '현재 관찰을 비교 기준으로 사용', clear: '이 프로젝트 기록 지우고 끄기', clearAll: '모든 비교 기록 지우기',
  pinned: '직접 교체하거나 지우기 전까지 비교 기준을 유지합니다. 새 검사에서는 기준과 최신 관찰만 보관합니다.',
  unavailable: '상태를 읽을 수 있고 일관성이 확인된 완료 검사가 필요합니다. 실패하거나 오래된 검사는 저장된 관찰을 덮어쓰지 않습니다.',
  newerSaved: '다른 화면에서 더 최근 관찰을 저장했습니다. 이 프로젝트를 재검사한 뒤 비교하거나 기준을 교체하세요.',
  storageError: '비교 기록을 읽거나 저장하지 못했습니다. 다시 읽거나 재검사한 뒤 비교 기준을 교체하세요.', retry: '기록 다시 읽기',
  baseline: '저장된 비교 기준', current: '현재 관찰', latest: '마지막 저장 관찰',
  observed: '검사 시각', source: '현재 출처 열기', unknown: '미확인', unchanged: '동일', changed: '변경됨',
  none: '선언 없음', absent: '파일 없음', fieldUnknown: '기록 없음',
  limits: '보관된 메타데이터만 비교합니다. 잘린 값과 해시가 없는 출처는 미확인으로 남깁니다. 해시가 같아도 검증의 유효성이나 권한을 뜻하지 않습니다.',
  omitted: '일부 출처 경로는 보관 한도를 넘어 비교에 포함되지 않았습니다.',
  metadata: '선언된 상태', sources: '검사에서 관찰한 출처 식별 정보',
  packet: '패킷', objective: '목표', status: '선언된 상태', gates: '선언된 사용자 게이트', spec: '활성 SPEC', handoff: '재개 체크포인트',
};
const ja: ResumeCopy = {
  title: '再開前の変更比較',
  introduction: '作業を続ける前に保存した観察を比較してください。履歴は作業許可、保留パケットの再開、検証合格や承認の根拠ではありません。',
  privacy: '任意でこの端末のアプリ設定に目標・状態・ゲート・パス・出典ハッシュ・観察日時を保存します。文書本文は保存しません。最大8プロジェクト・合計192 KiBで、古い履歴は削除される場合があります。アプリ再起動やローカルアドレス変更後も記録は保持されます。',
  enable: '有効にして比較基準を保存', compare: '保存した基準と比較', close: '比較を閉じる',
  replace: '現在の観察を比較基準にする', clear: 'このプロジェクトの履歴を削除して無効化', clearAll: '比較履歴をすべて削除',
  pinned: '明示的に置換・削除するまで基準を保持します。更新時は基準と最新の観察のみを保存します。',
  unavailable: '状態を読める、一貫した完了検査が必要です。失敗・古い検査では保存した観察を置き換えません。',
  newerSaved: '別の画面で新しい観察が保存されています。このプロジェクトを再検査してから比較・基準の置換を行ってください。',
  storageError: '比較履歴を読み取り・保存できませんでした。再読み込みまたは再検査してから比較基準を置き換えてください。', retry: '履歴を再読み込み',
  baseline: '保存した比較基準', current: '現在の観察', latest: '最後に保存した観察',
  observed: '検査日時', source: '現在の出典を開く', unknown: '不明', unchanged: '同一', changed: '変更あり',
  none: '宣言なし', absent: 'ファイルなし', fieldUnknown: '記録なし',
  limits: '保存したメタデータのみを比較します。切り詰めた値やハッシュのない出典は不明のままです。ハッシュの一致は検証の有効性や許可を示しません。',
  omitted: '一部の出典パスは保存上限を超え、比較に含まれません。',
  metadata: '宣言された状態', sources: '検査で観察した出典識別情報',
  packet: 'パケット', objective: '目標', status: '宣言された状態', gates: '宣言されたオーナーゲート', spec: '有効なSPEC', handoff: '再開チェックポイント',
};
const zh: ResumeCopy = {
  title: '恢复前变更比较',
  introduction: '继续工作前请比较已保存的观察。历史记录不代表工作授权、重新启动已延期的数据包、验证通过或用户接受。',
  privacy: '可选择在此设备的应用设置中保存目标、状态、关卡、路径、来源哈希和观察时间，不保存文档正文。最多8个项目、总计192 KiB，旧项目记录可能被清除。应用重启或本地地址变更后记录仍会保留。',
  enable: '启用并保存比较基准', compare: '与保存的基准比较', close: '关闭比较',
  replace: '将当前观察设为比较基准', clear: '清除此项目记录并停用', clearAll: '清除所有比较记录',
  pinned: '比较基准会一直保留，直到您明确替换或清除。刷新时仅保留基准和最新观察。',
  unavailable: '需要状态可读且一致的已完成检查。失败或过期的检查不会替换已保存的观察。',
  newerSaved: '另一个视图已保存更新的观察。请重新检查此项目后再比较或替换基准。',
  storageError: '无法读取或保存比较记录。请重试或重新检查后再替换比较基准。', retry: '重新读取记录',
  baseline: '已保存的比较基准', current: '当前观察', latest: '最近保存的观察',
  observed: '检查时间', source: '打开当前来源', unknown: '未知', unchanged: '相同', changed: '已更改',
  none: '未声明', absent: '文件不存在', fieldUnknown: '未记录',
  limits: '仅比较保留的元数据。截断的值或缺少哈希的来源仍为未知。哈希相同不代表验证有效或已获授权。',
  omitted: '部分来源路径超出保留上限，未纳入比较。',
  metadata: '声明的状态', sources: '检查中观察到的来源标识',
  packet: '数据包', objective: '目标', status: '声明的状态', gates: '声明的用户关卡', spec: '当前SPEC', handoff: '恢复检查点',
};
export const resumeComparisonCopy: Record<Locale, ResumeCopy> = { en, ko, ja, 'zh-CN': zh };
