const en = {
  title: "Verification run records", read: "Read verification records", refresh: "Read records again", loading: "Reading records…",
  note: "Browse linked records, then select one to compare its source files. Inspector does not run these commands or accept the work.",
  listRead: "List read at", choose: "Only registered paths are listed. Select a record to read its packet, result and current source comparison.",
  inspect: "Inspect record", selected: "Selected record", compareAgain: "Compare record again",
  pages: "Verification record pages", previous: "Previous records", next: "Next records",
  listChanged: "The record list changed. Read it again before selecting a record.", listUnavailable: "The current record routes could not be read. Check the project state and refresh the inspection.",
  connection: "Connect a collected record", connectionNote: "After collecting a receipt, run the connection preview from the SDAD source checkout with the project and receipt path. Review its suggested routed_docs entry, apply it yourself, then refresh this list. The preview changes no project files.",
  empty: "No verification receipts are linked in this project's routed documents. Existing written evidence remains available in its original location.",
  partial: "The record limit was reached. This is not the complete verification history.",
  failedLoad: "Could not read the records. Try again.", wrongProject: "The project or packet changed. Refresh the inspection before reading records again.",
  stale: "Refresh the inspection before reading verification records.", observed: "Compared at", details: "Recorded command and sources", scope: "Scope", requirement: "Requirement",
  source: "Source identity", log: "Retained log identity", matched: "Matches", changed: "Changed", unknown: "Cannot compare",
  passed: "Command succeeded", failed: "Command failed", timeout: "Timed out", start_failed: "Did not start", interrupted: "Interrupted",
  exit: "Exit code", ran: "Recorded run", historical: "Another packet", current: "Current packet", duringRun: "Source changed during the run", unknownRun: "Source stability during the run is unknown",
  retained: "Retained log bytes", total: "Observed output bytes", logPartial: "Only a bounded portion of the output was retained.",
  logIncomplete: "Output capture did not finish. Matching retained bytes do not prove the complete command output was observed.",
  openReceipt: "Show receipt file", openLog: "Show retained log", notProof: "Matching files and a successful command do not establish coverage of every requirement or user acceptance.",
};
export const verificationCopy: Record<"en" | "ko" | "ja" | "zh-CN", typeof en> = {
  en,
  ko: {
    title: "검증 실행 기록", read: "검증 기록 읽기", refresh: "검증 기록 다시 읽기", loading: "기록을 읽는 중…",
    note: "연결된 기록을 찾고 하나를 선택해 현재 파일과 대조합니다. Inspector가 명령을 실행하거나 작업을 수락하지는 않습니다.",
    listRead: "목록 조회 시각", choose: "등록된 경로만 표시합니다. 기록을 선택하면 작업 묶음, 실행 결과와 현재 파일 대조 결과를 읽습니다.",
    inspect: "기록 검사", selected: "선택한 기록", compareAgain: "이 기록 다시 대조",
    pages: "검증 기록 페이지", previous: "이전 기록", next: "다음 기록",
    listChanged: "기록 목록이 바뀌었습니다. 목록을 다시 읽은 뒤 기록을 선택하세요.", listUnavailable: "현재 기록 경로를 읽지 못했습니다. 프로젝트 상태를 확인하고 재검사하세요.",
    connection: "수집한 기록 연결하기", connectionNote: "기록 수집 후 SDAD 소스 폴더에서 프로젝트와 기록 경로를 지정해 연결 미리보기를 실행하세요. 제안된 routed_docs 항목을 확인해 직접 반영한 다음 목록을 다시 읽으세요. 미리보기는 프로젝트 파일을 변경하지 않습니다.",
    empty: "이 프로젝트의 문서 경로에 연결된 검증 실행 기록이 없습니다. 기존 문서 근거는 원래 위치에서 계속 확인할 수 있습니다.",
    partial: "표시할 기록 수의 한도에 도달했습니다. 전체 검증 이력이 아닙니다.",
    failedLoad: "기록을 읽지 못했습니다. 다시 시도하세요.", wrongProject: "프로젝트 또는 작업 묶음이 바뀌었습니다. 재검사한 뒤 기록을 다시 읽으세요.",
    stale: "재검사한 뒤 검증 기록을 읽으세요.", observed: "대조 시각", details: "실행 명령과 대상 파일", scope: "범위", requirement: "요구사항",
    source: "대상 파일", log: "보존된 로그", matched: "일치", changed: "변경됨", unknown: "비교 불가",
    passed: "명령 성공", failed: "명령 실패", timeout: "시간 초과", start_failed: "실행 시작 실패", interrupted: "실행 중단",
    exit: "종료 코드", ran: "기록된 실행", historical: "다른 작업 묶음", current: "현재 작업 묶음", duringRun: "실행 도중 대상 파일이 변경됨", unknownRun: "실행 도중 대상 파일의 안정성을 확인할 수 없음",
    retained: "보존된 로그 바이트", total: "관찰한 출력 바이트", logPartial: "출력의 일부만 한도 내에서 보존했습니다.",
    logIncomplete: "출력 수집이 끝나지 않았습니다. 보존된 바이트가 일치해도 전체 명령 출력을 관찰했다는 뜻은 아닙니다.",
    openReceipt: "실행 기록 파일 보기", openLog: "보존된 로그 보기", notProof: "파일 일치와 명령 성공만으로 모든 요구사항 충족이나 사용자 수락이 입증되지는 않습니다.",
  },
  ja: {
    title: "検証の実行記録", read: "検証記録を読む", refresh: "検証記録を再読込", loading: "記録を読み込み中…",
    note: "リンクされた記録から一つ選び、現在のファイルと比較します。Inspector はコマンドの実行や作業の受諾を行いません。",
    listRead: "一覧の読込日時", choose: "登録されたパスのみを表示します。記録を選ぶとパケット、実行結果、現在のファイルとの比較を読み込みます。",
    inspect: "記録を検査", selected: "選択した記録", compareAgain: "この記録を再比較",
    pages: "検証記録のページ", previous: "前の記録", next: "次の記録",
    listChanged: "記録一覧が変わりました。再読込してから記録を選択してください。", listUnavailable: "現在の記録パスを読めません。プロジェクト状態を確認して再検査してください。",
    connection: "収集した記録をリンク", connectionNote: "収集後、SDAD のソースフォルダーからプロジェクトと記録パスを指定して接続プレビューを実行してください。提案された routed_docs 項目を確認して手動で反映し、一覧を再読込してください。プレビューはプロジェクトを変更しません。",
    empty: "このプロジェクトの文書パスに検証実行記録がありません。既存の文書の証拠は元の場所で確認できます。",
    partial: "記録数の上限に達しました。検証履歴の全体ではありません。",
    failedLoad: "記録を読めませんでした。再試行してください。", wrongProject: "プロジェクトまたは作業パケットが変わりました。再検査後に記録を読んでください。",
    stale: "再検査後に検証記録を読んでください。", observed: "比較日時", details: "実行コマンドと対象ファイル", scope: "範囲", requirement: "要件",
    source: "対象ファイル", log: "保存ログ", matched: "一致", changed: "変更あり", unknown: "比較不可",
    passed: "コマンド成功", failed: "コマンド失敗", timeout: "時間切れ", start_failed: "開始失敗", interrupted: "中断",
    exit: "終了コード", ran: "記録された実行", historical: "別のパケット", current: "現在のパケット", duringRun: "実行中に対象ファイルが変更されました", unknownRun: "実行中のファイルの安定性は不明です",
    retained: "保存ログのバイト数", total: "観測した出力バイト数", logPartial: "出力の一部のみ上限内で保存しました。",
    logIncomplete: "出力の収集は完了していません。保存バイトの一致はコマンド出力全体を観測した証拠ではありません。",
    openReceipt: "実行記録ファイルを表示", openLog: "保存ログを表示", notProof: "ファイルの一致とコマンドの成功だけでは全要件の充足やユーザーの受諾を証明できません。",
  },
  "zh-CN": {
    title: "验证执行记录", read: "读取验证记录", refresh: "重新读取记录", loading: "正在读取记录…",
    note: "浏览已关联的记录，选择一条与当前文件比较。Inspector 不执行这些命令，也不确认验收。",
    listRead: "列表读取时间", choose: "仅列出已注册的路径。选择记录后读取工作包、执行结果及当前文件比较结果。",
    inspect: "检查记录", selected: "所选记录", compareAgain: "重新比较此记录",
    pages: "验证记录分页", previous: "上一页记录", next: "下一页记录",
    listChanged: "记录列表已更改。请重新读取后选择记录。", listUnavailable: "无法读取当前记录路径。请检查项目状态并重新检查。",
    connection: "关联已收集的记录", connectionNote: "收集后，在 SDAD 源码目录中指定项目和记录路径运行关联预览。检查建议的 routed_docs 条目并手动添加，然后刷新列表。预览不会更改项目文件。",
    empty: "此项目的文档路径未关联验证执行记录。现有书面证据仍可在原位置查看。",
    partial: "已达到记录数量限制。这不是完整的验证历史。",
    failedLoad: "无法读取记录，请重试。", wrongProject: "项目或工作包已更改。请重新检查后读取记录。",
    stale: "请重新检查后读取验证记录。", observed: "比较时间", details: "执行命令与源文件", scope: "范围", requirement: "需求",
    source: "目标文件", log: "保留的日志", matched: "一致", changed: "已更改", unknown: "无法比较",
    passed: "命令成功", failed: "命令失败", timeout: "超时", start_failed: "启动失败", interrupted: "已中断",
    exit: "退出码", ran: "已记录的执行", historical: "其他工作包", current: "当前工作包", duringRun: "执行期间目标文件发生变化", unknownRun: "无法确定执行期间目标文件的稳定性",
    retained: "保留日志字节数", total: "观测到的输出字节数", logPartial: "仅在限制范围内保留了部分输出。",
    logIncomplete: "输出收集未完成。保留字节一致并不表示已观测到完整命令输出。",
    openReceipt: "显示执行记录文件", openLog: "显示保留日志", notProof: "文件一致和命令成功并不证明所有需求均已满足或用户已验收。",
  },
};
